// Package conversation is the data-access layer over the conversations and
// messages tables. It keeps gateway handlers thin and persistence unit-testable;
// it contains no HTTP or vLLM types.
//
// Session ids are gateway-issued: CreateConversation returns a row whose id (the
// session id) is generated by the database. Every read and write is scoped by
// api_key_id so one credential can never touch another's conversation.
package conversation

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ErrNotFound is returned when a conversation does not exist for the given
// credential (a wrong owner is indistinguishable from a missing row).
var ErrNotFound = errors.New("conversation: not found")

// Role values stored in messages.role.
const (
	RoleSystem    = "system"
	RoleUser      = "user"
	RoleAssistant = "assistant"
)

// Conversation is a stored conversation. ID is the gateway-issued session id.
type Conversation struct {
	ID        string
	APIKeyID  string
	Model     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Message is a stored message.
type Message struct {
	ID             string
	ConversationID string
	Role           string
	Content        string
	TokenCount     *int
	CreatedAt      time.Time
}

// NewMessage is a message to append.
type NewMessage struct {
	Role       string
	Content    string
	TokenCount *int
}

// Repository reads and writes conversations and messages over a pgx pool.
type Repository struct {
	pool *pgxpool.Pool
}

// NewRepository returns a Repository backed by pool.
func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{pool: pool}
}

const conversationColumns = `id, api_key_id, COALESCE(model, ''), created_at, updated_at`

// CreateConversation creates a new conversation owned by apiKeyID and returns it
// with its server-issued id (the session id). An empty model is stored as NULL.
func (r *Repository) CreateConversation(ctx context.Context, apiKeyID, model string) (Conversation, error) {
	const q = `INSERT INTO conversations (api_key_id, model)
		VALUES ($1, NULLIF($2, ''))
		RETURNING ` + conversationColumns
	c, err := scanConversation(r.pool.QueryRow(ctx, q, apiKeyID, model))
	if err != nil {
		return Conversation{}, fmt.Errorf("conversation: creating: %w", err)
	}
	return c, nil
}

// GetConversation fetches a conversation scoped to its owning credential. A
// missing row or a wrong owner both return ErrNotFound.
func (r *Repository) GetConversation(ctx context.Context, apiKeyID, sessionID string) (Conversation, error) {
	const q = `SELECT ` + conversationColumns + `
		FROM conversations WHERE api_key_id = $1 AND id = $2`
	c, err := scanConversation(r.pool.QueryRow(ctx, q, apiKeyID, sessionID))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Conversation{}, ErrNotFound
		}
		return Conversation{}, fmt.Errorf("conversation: fetching: %w", err)
	}
	return c, nil
}

// LoadHistory returns a conversation's messages oldest-first.
func (r *Repository) LoadHistory(ctx context.Context, conversationID string) ([]Message, error) {
	const q = `SELECT id, conversation_id, role, content, token_count, created_at
		FROM messages WHERE conversation_id = $1 ORDER BY created_at, id`
	rows, err := r.pool.Query(ctx, q, conversationID)
	if err != nil {
		return nil, fmt.Errorf("conversation: loading history: %w", err)
	}
	defer rows.Close()

	var msgs []Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(&m.ID, &m.ConversationID, &m.Role, &m.Content, &m.TokenCount, &m.CreatedAt); err != nil {
			return nil, fmt.Errorf("conversation: scanning message: %w", err)
		}
		msgs = append(msgs, m)
	}
	return msgs, rows.Err()
}

// AppendMessages inserts msgs in a single transaction and bumps the
// conversation's updated_at. It is atomic: if any insert fails, nothing is
// persisted. Messages are written with strictly increasing timestamps so
// LoadHistory returns them in append order even within one batch. A non-existent
// conversation returns ErrNotFound.
func (r *Repository) AppendMessages(ctx context.Context, conversationID string, msgs []NewMessage) error {
	if len(msgs) == 0 {
		return nil
	}
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("conversation: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	base := time.Now().UTC()
	for i, m := range msgs {
		ts := base.Add(time.Duration(i) * time.Microsecond)
		if _, err := tx.Exec(ctx,
			`INSERT INTO messages (conversation_id, role, content, token_count, created_at)
				VALUES ($1, $2, $3, $4, $5)`,
			conversationID, m.Role, m.Content, m.TokenCount, ts); err != nil {
			return fmt.Errorf("conversation: appending message: %w", err)
		}
	}

	ct, err := tx.Exec(ctx, `UPDATE conversations SET updated_at = now() WHERE id = $1`, conversationID)
	if err != nil {
		return fmt.Errorf("conversation: bumping updated_at: %w", err)
	}
	if ct.RowsAffected() == 0 {
		return ErrNotFound
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("conversation: commit: %w", err)
	}
	return nil
}

type rowScanner interface {
	Scan(dest ...any) error
}

func scanConversation(s rowScanner) (Conversation, error) {
	var c Conversation
	err := s.Scan(&c.ID, &c.APIKeyID, &c.Model, &c.CreatedAt, &c.UpdatedAt)
	return c, err
}
